### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [80, 12, 3, 3], expected input[1, 16, 224, 320] to have 12 channels, but got 16 channels instead

### ISSUE THREAD

**Issue by Trevo1** [FatemeZamanian/Yolov5-Fruit-Detector#2]
i have no idea😭

**Comment by FatemeZamanian** [comment]
I run this project right now , just read readme and do steps 
mybe help  :
https://github.com/ultralytics/yolov5/issues/5183

**Comment by Trevo1** [comment]
> 
thanks, but it still doesn't work .. I think it maybe the model channels are mismatch, 
i am AI rookie, can't solve it 🤦‍♂️

**Comment by FatemeZamanian** [comment]
very well
Just tell me if you want to get inference only ???
And do you have a problem with this?

**Comment by Trevo1** [comment]
> very well Just tell me if you want to get inference only ??? And do you have a problem with this?

yes，and I get this error when I select a picture to start inference

**Comment by Trevo1** [comment]
it works in my another PC, with cpu-torch, it's wired 🫠 
Thanks again!

**Comment by FatemeZamanian** [comment]
I was working on this and it worked on both of them.
Your problem is the installation of dependencies
Good luck :)
