### ISSUE TITLE
Out of date model

### ISSUE THREAD

**Issue by BhooshanDeshpande** [FatemeZamanian/Yolov5-Fruit-Detector#4]
Got this error while working on the trained model. 
`AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'`

It points to -- 
`
https://github.com/ultralytics/yolov5/issues/6948
`
It says, probably due to out of date model [here](https://github.com/ultralytics/yolov5/issues/6948#issuecomment-1075478933).

**Comment by Asimoedeus** [comment]
Thank you! Really helpful.

In short: 

`def forward(self, input: Tensor) -> Tensor:
    return F.interpolate(input, self.size, self.scale_factor, self.mode, self.align_corners,
                         #recompute_scale_factor=self.recompute_scale_factor
)
 `     



Comment out the "recompute_scale_factor=self.recompute_scale_factor" parameter
